package logging

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestNewCreatesJSONLogInHomeDirectory(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	logger, err := New(context.Background())
	if err != nil {
		t.Fatalf("new logger: %v", err)
	}
	t.Cleanup(func() {
		if closeErr := logger.Close(); closeErr != nil {
			t.Fatalf("close logger: %v", closeErr)
		}
	})

	logger.Logger.Info("test-entry", "key", "value")

	logPath := logger.Path()
	if !strings.HasPrefix(logPath, filepath.Join(home, ".sc3", "logs")) {
		t.Fatalf("log path = %q, want prefix %q", logPath, filepath.Join(home, ".sc3", "logs"))
	}

	// #nosec G304 -- logPath is generated by logger.New() under temp HOME.
	content, err := os.ReadFile(logPath)
	if err != nil {
		t.Fatalf("read log file: %v", err)
	}
	if !strings.Contains(string(content), "\"msg\":\"test-entry\"") {
		t.Fatalf("log file does not contain JSON message entry: %s", string(content))
	}
}
